<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

use Magento\Framework\Escaper;

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');
$analyticsTypes = $block->getData('analyticsTypes');
$eventData = $viewModel->getEventData($analyticsTypes);
?>

<div x-data='{
    eventData: <?= $eventData ?>
}' x-init='() => {
    Tweakwise_Hyva_Analytics({
        eventData: eventData
    }).init();
}'>
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/analytics.js')); ?>"></script>
