name: Testing Suite
on: [push, workflow_dispatch]
jobs:
  linter:
    strategy:
      matrix:
        image: [
          'srcoder/development-php:php82-fpm'
        ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Testing Suite
        run: |
          composer install youwe/coding-standard-magento2
          composer install youwe/testing-suite
          vendor/bin/grumphp run --no-interaction
        shell: bash
